import { ACCOUNT_DEFS, CATEGORIES, rollAmount, validateEntry, applyEntry, summarize, calculateScore, isBlackProfitInsolvent } from './src/game-core.mjs';

const initialLedger = () => ({現金:100000, 資本金:100000});
const state = {
  player: 0, turn: 1, d1:null, d2:null, amount:0, selectedSide:'debit',
  players:[{name:'プレイヤー1',ledger:initialLedger(),entries:[]},{name:'プレイヤー2',ledger:initialLedger(),entries:[]}],
  filters:'すべて', finished:false
};
const $=id=>document.getElementById(id); const fmt=n=>`${Number(n).toLocaleString('ja-JP')}円`;
const accounts=Object.entries(ACCOUNT_DEFS);

function current(){return state.players[state.player]}
function renderAll(){renderHeader();renderDice();renderRows();renderFilters();renderAccounts();renderCompany();renderHistory();}
function renderHeader(){ $('playerName').textContent=current().name; $('turn').textContent=state.turn; document.querySelectorAll('.player-tab').forEach((b,i)=>b.classList.toggle('active',i===state.player)); }
function renderDice(){ $('amount').textContent=state.amount?fmt(state.amount):'まだ振っていません'; if(state.amount){$('dicePanel').classList.remove('hidden');$('d1').textContent=state.d1;$('d2').textContent=state.d2;$('amountBig').textContent=fmt(state.amount)} else $('dicePanel').classList.add('hidden'); }
function renderFilters(){const box=$('filters');box.innerHTML='';['すべて',...CATEGORIES].forEach(c=>{const b=document.createElement('button');b.className=`filter-chip ${state.filters===c?'active':''}`;b.textContent=c;b.onclick=()=>{state.filters=c;renderFilters();renderAccounts()};box.appendChild(b)})}
function renderAccounts(){const box=$('accounts');box.innerHTML='';for(const [name,[category,side]] of accounts){if(state.filters!=='すべて'&&category!==state.filters)continue;const b=document.createElement('button');b.className='account-card';b.draggable=true;b.dataset.account=name;b.innerHTML=`<strong>${name}</strong><small>${category} / 通常${side}</small>`;b.onclick=()=>addAccount(name,state.selectedSide);b.ondragstart=e=>e.dataTransfer.setData('text/account',name);box.appendChild(b)}}
function addAccount(name,side){if(!state.amount){show('先にサイコロを振ってください');return}const box=$(side==='debit'?'debitRows':'creditRows');box.querySelector('.empty')?.remove();const row=document.createElement('div');row.className='entry-row';const select=document.createElement('select');for(const [n] of accounts){const o=document.createElement('option');o.value=n;o.textContent=n;o.selected=n===name;select.appendChild(o)}const input=document.createElement('input');input.type='number';input.min='1';input.step='1000';input.placeholder='金額';input.value=state.amount;const rm=document.createElement('button');rm.className='remove';rm.textContent='×';rm.onclick=()=>{row.remove();refreshRows()};row.append(select,input,rm);box.appendChild(row);refreshRows()}
function renderRows(){refreshRows();document.querySelectorAll('.side-choice').forEach(b=>b.classList.toggle('active',b.dataset.side===state.selectedSide))}
function refreshRows(){for(const id of ['debitRows','creditRows']){const box=$(id);if(!box.querySelector('.entry-row'))box.innerHTML='<div class="empty">ここへ勘定科目を置く</div>'}const total=s=>[...$(s==='debit'?'debitRows':'creditRows').querySelectorAll('.entry-row')].reduce((n,r)=>n+Number(r.querySelector('input').value||0),0);$('debitTotal').textContent=fmt(total('debit'));$('creditTotal').textContent=fmt(total('credit'));$('postBtn').disabled=!state.amount||state.finished}
function getEntry(){const read=s=>[...$(s==='debit'?'debitRows':'creditRows').querySelectorAll('.entry-row')].map(r=>({account:r.querySelector('select').value,amount:Number(r.querySelector('input').value||0)}));return{debits:read('debit'),credits:read('credit')}}
function clearJournal(){$('debitRows').innerHTML='<div class="empty">ここへ勘定科目を置く</div>';$('creditRows').innerHTML='<div class="empty">ここへ勘定科目を置く</div>';refreshRows()}
function show(t,ok=false){$('message').textContent=t;$('message').className=`message${ok?' ok':''}`}
function roll(){if(state.finished)return;state.d1=Math.floor(Math.random()*10)+1;state.d2=Math.floor(Math.random()*4)+1;state.amount=rollAmount(state.d1,state.d2);clearJournal();renderDice();refreshRows();show(`${current().name}：${fmt(state.amount)}を使って、何をするか自分で決めてください。`,true)}
function post(){const entry=getEntry();const errors=validateEntry(entry,state.amount);if(errors.length){show(errors.join(' / '));return}applyEntry(current().ledger,entry);current().entries.push({turn:state.turn,amount:state.amount,...entry});show('仕訳を帳簿へ反映しました。次のプレイヤーへ。',true);state.amount=0;clearJournal();state.player=state.player?0:1;if(state.player===0)state.turn++;renderAll()}
function renderCompany(){const s=summarize(current().ledger);$('cashState').textContent=`現金 ${fmt(current().ledger.現金||0)}`;$('netIncome').textContent=fmt(s.netIncome);$('netAssets').textContent=fmt(s.netAssets);$('revenue').textContent=fmt(s.revenue);$('expense').textContent=fmt(s.expense);$('score').textContent=calculateScore(s.netAssets,s.revenue).toLocaleString('ja-JP')}
function renderHistory(){const box=$('history');box.innerHTML='';const entries=current().entries;$('historyCount').textContent=`${entries.length}件`;for(const e of entries.slice().reverse()){const div=document.createElement('div');div.className='history-item';div.innerHTML=`<b>${e.turn}ターン / ${fmt(e.amount)}</b><br>借方：${e.debits.map(x=>`${x.account} ${fmt(x.amount)}`).join('・')}<br>貸方：${e.credits.map(x=>`${x.account} ${fmt(x.amount)}`).join('・')}`;box.appendChild(div)}}
function finishGame(){if(state.players.some(p=>p.entries.length===0)){show('両プレイヤーが1回以上仕訳してから決算してください');return}state.finished=true;const results=state.players.map(p=>{const s=summarize(p.ledger);return{...s,score:calculateScore(s.netAssets,s.revenue),bankrupt:isBlackProfitInsolvent(p.ledger.現金||0,s.liabilities,s.netIncome)}});let text='';if(results.some(r=>r.bankrupt)){const names=results.map((r,i)=>r.bankrupt?`プレイヤー${i+1}`:null).filter(Boolean).join('・');text=`${names}：黒字倒産。スコアに関係なく負けです。`}else if(results[0].score===results[1].score){text='同点です。'}else{text=`プレイヤー${results[0].score>results[1].score?'1':'2'}のスコアが高く、勝利です。`}show(text,true);$('result').classList.remove('hidden');$('resultBody').innerHTML=results.map((r,i)=>`<div class="result-card"><strong>プレイヤー${i+1}</strong><span>純利益 ${fmt(r.netIncome)}</span><span>純資産 ${fmt(r.netAssets)}</span><span>スコア ${r.score.toLocaleString('ja-JP')}</span><span>${r.bankrupt?'黒字倒産：負け':'黒字倒産なし'}</span></div>`).join('')}
function reset(){state.player=0;state.turn=1;state.d1=null;state.d2=null;state.amount=0;state.selectedSide='debit';state.players=[{name:'プレイヤー1',ledger:initialLedger(),entries:[]},{name:'プレイヤー2',ledger:initialLedger(),entries:[]}];state.filters='すべて';state.finished=false;$('result').classList.add('hidden');show('');renderAll()}
$('rollBtn').onclick=roll;$('postBtn').onclick=post;$('finishBtn').onclick=finishGame;$('resetBtn').onclick=reset;$('filterBtn').onclick=()=>$('filters').classList.toggle('hidden');document.querySelectorAll('.side-choice').forEach(b=>b.onclick=()=>{state.selectedSide=b.dataset.side;renderRows()});document.querySelectorAll('.player-tab').forEach(b=>b.onclick=()=>{if(!state.amount&&!state.finished){state.player=Number(b.dataset.player);renderAll()}});document.querySelectorAll('.add-row').forEach(b=>b.onclick=()=>addAccount('現金',b.dataset.side));for(const z of document.querySelectorAll('.dropzone')){z.ondragover=e=>e.preventDefault();z.ondrop=e=>{e.preventDefault();const n=e.dataTransfer.getData('text/account');if(n)addAccount(n,z.dataset.side)}}
renderAll();
